#cloud-config
repo_update: true
repo_upgrade: all

packages:
  - mysql-server
  - postgresql94-server

runcmd:
  - cp /usr/share/zoneinfo/Asia/Tokyo /etc/localtime
  - chkconfig mysqld on
  - service mysqld start
  - chkconfig postgresql94 on
  - service postgresql94 initdb
  - service postgresql94 start
