#cloud-config
repo_update: true
repo_upgrade: all

packages:
  - nginx

runcmd:
  - sed -i -E 's@^(ZONE=).*@\1"Asia/Tokyo"@' /etc/sysconfig/clock
  - cp /usr/share/zoneinfo/Asia/Tokyo /etc/localtime
  - service nginx start
  - chkconfig nginx on
  - uname -n > /usr/share/nginx/html/index.html
