#cloud-config
repo_update: true
repo_upgrade: all
timezone: "Asia/Tokyo"

packages:
  - mysql
  - nginx
  - php56

runcmd:
  - pip install memcache-cli
  - chkconfig nginx on
  - service nginx start
  - uname -n > /usr/share/nginx/html/index.html
