---
- name: Get latest wordpress
  get_url:
    url: http://ja.wordpress.org/latest-ja.tar.gz
    dest: /tmp/latest-ja.tar.gz

- name: Unarchive
  unarchive:
    src: /tmp/latest-ja.tar.gz
    dest: /var/www/html
    copy: no

- name: Change owner to apache
  file:
    path: /var/www/html/wordpress
    owner: apache
    group: apache
    recurse: yes
