#cloud-config
repo_update: true
repo_upgrade: all
timezone: "Asia/Tokyo"

runcmd:
  - gem install aws-sdk-core

# Local Variables:
# mode: Shell-Script
# sh-indentation: 2
# indent-tabs-mode: nil
# sh-basic-offset: 2
# End:
# vim: ft=sh sw=2 ts=2 et
